"""usuarios adicionais

Revision ID: 18d2726ebaad
Revises: 314c21e167c2
Create Date: 2025-11-30 22:20:41.523781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18d2726ebaad'
down_revision: Union[str, Sequence[str], None] = '314c21e167c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('declarante', 'tipo_envolvimento',
               existing_type=sa.VARCHAR(length=27),
               type_=sa.Enum('DECLARANTE', 'VITIMA', 'AUTOR', 'SUSPEITO', 'TESTEMUNHA', 'OUTRO', name='tipoenvolvimento'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('declarante', 'tipo_envolvimento',
               existing_type=sa.Enum('DECLARANTE', 'VITIMA', 'AUTOR', 'SUSPEITO', 'TESTEMUNHA', 'OUTRO', name='tipoenvolvimento'),
               type_=sa.VARCHAR(length=27),
               existing_nullable=False)
    # ### end Alembic commands ###
