"""tabelas criadas

Revision ID: ad1509f2a00e
Revises: 
Create Date: 2025-11-28 19:42:04.821483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad1509f2a00e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('posto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lotacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_autor')
    )
    op.create_table('declarante',
    sa.Column('id_declarante', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_envolvimento', sa.Enum('DECLARANTE', 'VITIMA', 'AUTOR', 'SUSPEITO', 'TESTEMUNHA', 'CONDUTOR', 'PASSAGEIRO', 'PEDESTRE', 'REPRESENTANTE_LEGAL', 'PROPRIETARIO', 'ACIONANTE', 'INDICIADO', 'SOCORRISTA', 'RESPONSAVEL_ESTABELECIMENTO', 'OUTRO', name='tipoenvolvimento'), nullable=False),
    sa.PrimaryKeyConstraint('id_declarante')
    )
    op.create_table('boletimocorrencia',
    sa.Column('id_boletim', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('tipo_ocorrencia', sa.Enum('FURTO', 'ROUBO', 'HOMICIDIO', 'LESAO_CORPORAL', 'AMEACA', 'VIOLENCIA_DOMESTICA', 'ESTELIONATO', 'DANOS_MATERIAIS', 'ACIDENTE_TRANSITO', 'EMBRIAGUEZ_AO_VOLANTE', 'DESAPARECIMENTO_PESSOA', 'ENCONTRO_CADAVER', 'ENCONTRO_PESSOA', 'PERTURBACAO_TRANQUILIDADE', 'VIOLACAO_DOMICILIO', 'DANO', 'POSSE_DROGAS', 'TRAFICO_DROGAS', 'PORTE_ARMA', 'RECEPTACAO', 'CRIME_CIBERNETICO', 'FRAUDE', 'DIFAMACAO', 'INJURIA', 'CALUNIA', 'DESOBEDIENCIA', 'DESACATO', 'VIOLACAO_MEDIDA_PROTETIVA', 'TENTATIVA_SUICIDIO', 'MAUS_TRATOS_ANIMAIS', 'OUTROS', name='tipoocorrencia'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('REGISTRADO', 'EM_ANALISE', 'EM_INVESTIGACAO', 'COMPLEMENTADO', 'ENCAMINHADO', 'SUSPENSO', 'ARQUIVADO', 'CONCLUIDO', 'CANCELADO', 'AGUARDANDO_VALIDACAO', 'REABERTO', name='statusboletim'), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id_autor'], ),
    sa.PrimaryKeyConstraint('id_boletim')
    )
    op.create_table('declaranteboletim',
    sa.Column('declarante_id', sa.Integer(), nullable=False),
    sa.Column('boletim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boletim_id'], ['boletimocorrencia.id_boletim'], ),
    sa.ForeignKeyConstraint(['declarante_id'], ['declarante.id_declarante'], ),
    sa.PrimaryKeyConstraint('declarante_id', 'boletim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('declaranteboletim')
    op.drop_table('boletimocorrencia')
    op.drop_table('declarante')
    op.drop_table('autor')
    # ### end Alembic commands ###
